### ISSUE TITLE
NvidiaInspector Profile error

### ISSUE THREAD

**Issue by Trshhh** [Natram1zh/Apex-Autoexec-And-Tweaks-#1]
I get this error message when i try to import the NvidiaInspector profile

Some profile(s) could not imported! 

Failed to import 'Base Profile' - DRS_SetSetting failed: NVAPI_NOT_SUPPORTED

any idea what the issue could be?

**Comment by Natram1zh** [comment]
Sry for the late reply, you must be using latest driver (above 496.13 is not supported) or very old driver. soon i will update the profile.

**Comment by Natram1zh** [comment]
Check now, i have updated it
[New Profile For 496.13 And Above.zip](https://github.com/Natram1zh/Apex-Autoexec-And-Tweaks-/files/7776774/New.Profile.For.496.13.And.Above.zip)
.
