### ISSUE TITLE
How do I revert the windows full screen / game bar regedit changes?

### ISSUE THREAD

**Issue by mikkelens** [Natram1zh/Apex-Autoexec-And-Tweaks-#2]
I tried the windows tweaks and now I can't take screenshots using Win+Shift+S, which I am used to for most of my games. How do I reset these changes?

**Comment by Natram1zh** [comment]
sry for late reply i was grinding rank. try this ..

[Disable FSE And Allow Gamebar.zip](https://github.com/Natram1zh/Apex-Autoexec-And-Tweaks-/files/8166952/Disable.FSE.And.Allow.Gamebar.zip)

if it don't work then use lightshot.  btw always have backup or create restore point while doing windows tweaks.
